server:
  port:8080

eureka:
  client:
    register-with-eureka:true
    fetch-registery:true
  defaultZone: http://localhost:8761/eureka-server/

server:
  wait-time-in-ms-sync-empty:false

spring:
  application-name:eureka-sever

